            - name: Bolt by Koalalab
  # You may pin to the exact commit or the version.
  # uses: koalalab-inc/bolt@98e1363730b62fc8d3aa5a9a8e5605f875573851
  uses: koalalab-inc/bolt@v1.0.0
  with:
    # Mode of operation - audit or block
    mode: # optional, default is audit
    # Allow HTTP traffic
    allow_http: # optional
    # Default policy for egress traffic - allow-all or block-all
    default_policy: # optional, default is block-all
    # Egress rules
    egress_rules: # optional, default is []
          
